NOTI_PORT: 9011

MARIADB_HOST: 10.10.10.10
MARIADB_PORT: 3306
MARIADB_USER: superuser
MARIADB_PWD: mypwd

SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE: 10

APP_TEMPLATE_LOCATION: C:\\Users\\shamsul.saleh\\temp\\